# Generated by Django 5.1.1 on 2024-09-09 15:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my_first_app", "0004_remove_book_publisher_author_book_authors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="publisher",
        ),
    ]
